Product:
    type: entity
    table: product
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        price:
            type: integer
            nullable: true
            options:
                unsigned: false
        description:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        stock:
            type: integer
            nullable: true
            options:
                unsigned: false
        image:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        category:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
