Utilisateurs:
    type: entity
    table: utilisateurs
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        civilite:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        nom:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        prenom:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        tel:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        adresse:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        ville:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        pays:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        login:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        password:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        codepostal:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
        email:
            type: text
            nullable: true
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
